// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.18.1
// source: Proto/starwars.proto

package Proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Comandos int32

const (
	Comandos_AddCity      Comandos = 0
	Comandos_UpdateName   Comandos = 1
	Comandos_UpdateNumber Comandos = 2
	Comandos_DeleteCity   Comandos = 3
)

// Enum value maps for Comandos.
var (
	Comandos_name = map[int32]string{
		0: "AddCity",
		1: "UpdateName",
		2: "UpdateNumber",
		3: "DeleteCity",
	}
	Comandos_value = map[string]int32{
		"AddCity":      0,
		"UpdateName":   1,
		"UpdateNumber": 2,
		"DeleteCity":   3,
	}
)

func (x Comandos) Enum() *Comandos {
	p := new(Comandos)
	*p = x
	return p
}

func (x Comandos) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Comandos) Descriptor() protoreflect.EnumDescriptor {
	return file_Proto_starwars_proto_enumTypes[0].Descriptor()
}

func (Comandos) Type() protoreflect.EnumType {
	return &file_Proto_starwars_proto_enumTypes[0]
}

func (x Comandos) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Comandos.Descriptor instead.
func (Comandos) EnumDescriptor() ([]byte, []int) {
	return file_Proto_starwars_proto_rawDescGZIP(), []int{0}
}

type SolicitudRecibirComando struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd *Comando `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
}

func (x *SolicitudRecibirComando) Reset() {
	*x = SolicitudRecibirComando{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_starwars_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SolicitudRecibirComando) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudRecibirComando) ProtoMessage() {}

func (x *SolicitudRecibirComando) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_starwars_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudRecibirComando.ProtoReflect.Descriptor instead.
func (*SolicitudRecibirComando) Descriptor() ([]byte, []int) {
	return file_Proto_starwars_proto_rawDescGZIP(), []int{0}
}

func (x *SolicitudRecibirComando) GetCmd() *Comando {
	if x != nil {
		return x.Cmd
	}
	return nil
}

type RespuestaRecibirComandoMosEisley struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DirFulcrum string `protobuf:"bytes,1,opt,name=dir_fulcrum,json=dirFulcrum,proto3" json:"dir_fulcrum,omitempty"`
}

func (x *RespuestaRecibirComandoMosEisley) Reset() {
	*x = RespuestaRecibirComandoMosEisley{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_starwars_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespuestaRecibirComandoMosEisley) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaRecibirComandoMosEisley) ProtoMessage() {}

func (x *RespuestaRecibirComandoMosEisley) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_starwars_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaRecibirComandoMosEisley.ProtoReflect.Descriptor instead.
func (*RespuestaRecibirComandoMosEisley) Descriptor() ([]byte, []int) {
	return file_Proto_starwars_proto_rawDescGZIP(), []int{1}
}

func (x *RespuestaRecibirComandoMosEisley) GetDirFulcrum() string {
	if x != nil {
		return x.DirFulcrum
	}
	return ""
}

type RespuestaRecibirComandoFulcrum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RelojVec *RelojVector `protobuf:"bytes,1,opt,name=reloj_vec,json=relojVec,proto3" json:"reloj_vec,omitempty"`
}

func (x *RespuestaRecibirComandoFulcrum) Reset() {
	*x = RespuestaRecibirComandoFulcrum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_starwars_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespuestaRecibirComandoFulcrum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaRecibirComandoFulcrum) ProtoMessage() {}

func (x *RespuestaRecibirComandoFulcrum) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_starwars_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaRecibirComandoFulcrum.ProtoReflect.Descriptor instead.
func (*RespuestaRecibirComandoFulcrum) Descriptor() ([]byte, []int) {
	return file_Proto_starwars_proto_rawDescGZIP(), []int{2}
}

func (x *RespuestaRecibirComandoFulcrum) GetRelojVec() *RelojVector {
	if x != nil {
		return x.RelojVec
	}
	return nil
}

type SolicitudGetNumberRebelds struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coord *Ubicacion `protobuf:"bytes,1,opt,name=coord,proto3" json:"coord,omitempty"`
}

func (x *SolicitudGetNumberRebelds) Reset() {
	*x = SolicitudGetNumberRebelds{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_starwars_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SolicitudGetNumberRebelds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudGetNumberRebelds) ProtoMessage() {}

func (x *SolicitudGetNumberRebelds) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_starwars_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudGetNumberRebelds.ProtoReflect.Descriptor instead.
func (*SolicitudGetNumberRebelds) Descriptor() ([]byte, []int) {
	return file_Proto_starwars_proto_rawDescGZIP(), []int{3}
}

func (x *SolicitudGetNumberRebelds) GetCoord() *Ubicacion {
	if x != nil {
		return x.Coord
	}
	return nil
}

type RespuestaGetNumberRebelds struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumRebels int64        `protobuf:"varint,1,opt,name=num_rebels,json=numRebels,proto3" json:"num_rebels,omitempty"`
	RelojVec  *RelojVector `protobuf:"bytes,2,opt,name=reloj_vec,json=relojVec,proto3" json:"reloj_vec,omitempty"`
}

func (x *RespuestaGetNumberRebelds) Reset() {
	*x = RespuestaGetNumberRebelds{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_starwars_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespuestaGetNumberRebelds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaGetNumberRebelds) ProtoMessage() {}

func (x *RespuestaGetNumberRebelds) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_starwars_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaGetNumberRebelds.ProtoReflect.Descriptor instead.
func (*RespuestaGetNumberRebelds) Descriptor() ([]byte, []int) {
	return file_Proto_starwars_proto_rawDescGZIP(), []int{4}
}

func (x *RespuestaGetNumberRebelds) GetNumRebels() int64 {
	if x != nil {
		return x.NumRebels
	}
	return 0
}

func (x *RespuestaGetNumberRebelds) GetRelojVec() *RelojVector {
	if x != nil {
		return x.RelojVec
	}
	return nil
}

type Comando struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Comando    Comandos   `protobuf:"varint,1,opt,name=comando,proto3,enum=Proto.Comandos" json:"comando,omitempty"`
	Coord      *Ubicacion `protobuf:"bytes,2,opt,name=coord,proto3" json:"coord,omitempty"`
	NuevoValor string     `protobuf:"bytes,4,opt,name=nuevo_valor,json=nuevoValor,proto3" json:"nuevo_valor,omitempty"`
}

func (x *Comando) Reset() {
	*x = Comando{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_starwars_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Comando) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comando) ProtoMessage() {}

func (x *Comando) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_starwars_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comando.ProtoReflect.Descriptor instead.
func (*Comando) Descriptor() ([]byte, []int) {
	return file_Proto_starwars_proto_rawDescGZIP(), []int{5}
}

func (x *Comando) GetComando() Comandos {
	if x != nil {
		return x.Comando
	}
	return Comandos_AddCity
}

func (x *Comando) GetCoord() *Ubicacion {
	if x != nil {
		return x.Coord
	}
	return nil
}

func (x *Comando) GetNuevoValor() string {
	if x != nil {
		return x.NuevoValor
	}
	return ""
}

type RelojVector struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	X    int64  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y    int64  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	Z    int64  `protobuf:"varint,4,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *RelojVector) Reset() {
	*x = RelojVector{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_starwars_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RelojVector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelojVector) ProtoMessage() {}

func (x *RelojVector) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_starwars_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelojVector.ProtoReflect.Descriptor instead.
func (*RelojVector) Descriptor() ([]byte, []int) {
	return file_Proto_starwars_proto_rawDescGZIP(), []int{6}
}

func (x *RelojVector) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RelojVector) GetX() int64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *RelojVector) GetY() int64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *RelojVector) GetZ() int64 {
	if x != nil {
		return x.Z
	}
	return 0
}

type Ubicacion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NombrePlaneta string `protobuf:"bytes,1,opt,name=nombre_planeta,json=nombrePlaneta,proto3" json:"nombre_planeta,omitempty"`
	NombreCiudad  string `protobuf:"bytes,2,opt,name=nombre_ciudad,json=nombreCiudad,proto3" json:"nombre_ciudad,omitempty"`
}

func (x *Ubicacion) Reset() {
	*x = Ubicacion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_starwars_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ubicacion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ubicacion) ProtoMessage() {}

func (x *Ubicacion) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_starwars_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ubicacion.ProtoReflect.Descriptor instead.
func (*Ubicacion) Descriptor() ([]byte, []int) {
	return file_Proto_starwars_proto_rawDescGZIP(), []int{7}
}

func (x *Ubicacion) GetNombrePlaneta() string {
	if x != nil {
		return x.NombrePlaneta
	}
	return ""
}

func (x *Ubicacion) GetNombreCiudad() string {
	if x != nil {
		return x.NombreCiudad
	}
	return ""
}

var File_Proto_starwars_proto protoreflect.FileDescriptor

var file_Proto_starwars_proto_rawDesc = []byte{
	0x0a, 0x14, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x61, 0x72, 0x77, 0x61, 0x72, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3b, 0x0a,
	0x17, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x52, 0x65, 0x63, 0x69, 0x62, 0x69,
	0x72, 0x43, 0x6f, 0x6d, 0x61, 0x6e, 0x64, 0x6f, 0x12, 0x20, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f,
	0x6d, 0x61, 0x6e, 0x64, 0x6f, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x22, 0x43, 0x0a, 0x20, 0x52, 0x65,
	0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x52, 0x65, 0x63, 0x69, 0x62, 0x69, 0x72, 0x43, 0x6f,
	0x6d, 0x61, 0x6e, 0x64, 0x6f, 0x4d, 0x6f, 0x73, 0x45, 0x69, 0x73, 0x6c, 0x65, 0x79, 0x12, 0x1f,
	0x0a, 0x0b, 0x64, 0x69, 0x72, 0x5f, 0x66, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x69, 0x72, 0x46, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x22,
	0x51, 0x0a, 0x1e, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x52, 0x65, 0x63, 0x69,
	0x62, 0x69, 0x72, 0x43, 0x6f, 0x6d, 0x61, 0x6e, 0x64, 0x6f, 0x46, 0x75, 0x6c, 0x63, 0x72, 0x75,
	0x6d, 0x12, 0x2f, 0x0a, 0x09, 0x72, 0x65, 0x6c, 0x6f, 0x6a, 0x5f, 0x76, 0x65, 0x63, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x6c,
	0x6f, 0x6a, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x08, 0x72, 0x65, 0x6c, 0x6f, 0x6a, 0x56,
	0x65, 0x63, 0x22, 0x43, 0x0a, 0x19, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x47,
	0x65, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x62, 0x65, 0x6c, 0x64, 0x73, 0x12,
	0x26, 0x0a, 0x05, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x62, 0x69, 0x63, 0x61, 0x63, 0x69, 0x6f, 0x6e,
	0x52, 0x05, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x22, 0x6b, 0x0a, 0x19, 0x52, 0x65, 0x73, 0x70, 0x75,
	0x65, 0x73, 0x74, 0x61, 0x47, 0x65, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x62,
	0x65, 0x6c, 0x64, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x75, 0x6d, 0x5f, 0x72, 0x65, 0x62, 0x65,
	0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6e, 0x75, 0x6d, 0x52, 0x65, 0x62,
	0x65, 0x6c, 0x73, 0x12, 0x2f, 0x0a, 0x09, 0x72, 0x65, 0x6c, 0x6f, 0x6a, 0x5f, 0x76, 0x65, 0x63,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52,
	0x65, 0x6c, 0x6f, 0x6a, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x08, 0x72, 0x65, 0x6c, 0x6f,
	0x6a, 0x56, 0x65, 0x63, 0x22, 0x7d, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x61, 0x6e, 0x64, 0x6f, 0x12,
	0x29, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x61, 0x6e, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0f, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6d, 0x61, 0x6e, 0x64, 0x6f,
	0x73, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x61, 0x6e, 0x64, 0x6f, 0x12, 0x26, 0x0a, 0x05, 0x63, 0x6f,
	0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x55, 0x62, 0x69, 0x63, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x63, 0x6f, 0x6f,
	0x72, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x75, 0x65, 0x76, 0x6f, 0x5f, 0x76, 0x61, 0x6c, 0x6f,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x75, 0x65, 0x76, 0x6f, 0x56, 0x61,
	0x6c, 0x6f, 0x72, 0x22, 0x4b, 0x0a, 0x0b, 0x52, 0x65, 0x6c, 0x6f, 0x6a, 0x56, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x7a,
	0x22, 0x57, 0x0a, 0x09, 0x55, 0x62, 0x69, 0x63, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a,
	0x0e, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x50, 0x6c, 0x61,
	0x6e, 0x65, 0x74, 0x61, 0x12, 0x23, 0x0a, 0x0d, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x5f, 0x63,
	0x69, 0x75, 0x64, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6e, 0x6f, 0x6d,
	0x62, 0x72, 0x65, 0x43, 0x69, 0x75, 0x64, 0x61, 0x64, 0x2a, 0x49, 0x0a, 0x08, 0x43, 0x6f, 0x6d,
	0x61, 0x6e, 0x64, 0x6f, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x43, 0x69, 0x74, 0x79,
	0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x69,
	0x74, 0x79, 0x10, 0x03, 0x32, 0x0c, 0x0a, 0x0a, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x6e,
	0x74, 0x65, 0x32, 0xbe, 0x01, 0x0a, 0x09, 0x4d, 0x6f, 0x73, 0x45, 0x69, 0x73, 0x6c, 0x65, 0x79,
	0x12, 0x59, 0x0a, 0x0e, 0x52, 0x65, 0x63, 0x69, 0x62, 0x69, 0x72, 0x43, 0x6f, 0x6d, 0x61, 0x6e,
	0x64, 0x6f, 0x12, 0x1e, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x6f, 0x6c, 0x69, 0x63,
	0x69, 0x74, 0x75, 0x64, 0x52, 0x65, 0x63, 0x69, 0x62, 0x69, 0x72, 0x43, 0x6f, 0x6d, 0x61, 0x6e,
	0x64, 0x6f, 0x1a, 0x27, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x75,
	0x65, 0x73, 0x74, 0x61, 0x52, 0x65, 0x63, 0x69, 0x62, 0x69, 0x72, 0x43, 0x6f, 0x6d, 0x61, 0x6e,
	0x64, 0x6f, 0x4d, 0x6f, 0x73, 0x45, 0x69, 0x73, 0x6c, 0x65, 0x79, 0x12, 0x56, 0x0a, 0x10, 0x47,
	0x65, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x62, 0x65, 0x6c, 0x64, 0x73, 0x12,
	0x20, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75,
	0x64, 0x47, 0x65, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x62, 0x65, 0x6c, 0x64,
	0x73, 0x1a, 0x20, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65,
	0x73, 0x74, 0x61, 0x47, 0x65, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x62, 0x65,
	0x6c, 0x64, 0x73, 0x32, 0xba, 0x01, 0x0a, 0x07, 0x46, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x12,
	0x57, 0x0a, 0x0e, 0x52, 0x65, 0x63, 0x69, 0x62, 0x69, 0x72, 0x43, 0x6f, 0x6d, 0x61, 0x6e, 0x64,
	0x6f, 0x12, 0x1e, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69,
	0x74, 0x75, 0x64, 0x52, 0x65, 0x63, 0x69, 0x62, 0x69, 0x72, 0x43, 0x6f, 0x6d, 0x61, 0x6e, 0x64,
	0x6f, 0x1a, 0x25, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65,
	0x73, 0x74, 0x61, 0x52, 0x65, 0x63, 0x69, 0x62, 0x69, 0x72, 0x43, 0x6f, 0x6d, 0x61, 0x6e, 0x64,
	0x6f, 0x46, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x12, 0x56, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x62, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x20, 0x2e, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x47, 0x65,
	0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x62, 0x65, 0x6c, 0x64, 0x73, 0x1a, 0x20,
	0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61,
	0x47, 0x65, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x62, 0x65, 0x6c, 0x64, 0x73,
	0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69,
	0x72, 0x6f, 0x6a, 0x61, 0x73, 0x31, 0x34, 0x2f, 0x4c, 0x61, 0x62, 0x33, 0x49, 0x4e, 0x46, 0x33,
	0x34, 0x33, 0x2f, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Proto_starwars_proto_rawDescOnce sync.Once
	file_Proto_starwars_proto_rawDescData = file_Proto_starwars_proto_rawDesc
)

func file_Proto_starwars_proto_rawDescGZIP() []byte {
	file_Proto_starwars_proto_rawDescOnce.Do(func() {
		file_Proto_starwars_proto_rawDescData = protoimpl.X.CompressGZIP(file_Proto_starwars_proto_rawDescData)
	})
	return file_Proto_starwars_proto_rawDescData
}

var file_Proto_starwars_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Proto_starwars_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_Proto_starwars_proto_goTypes = []interface{}{
	(Comandos)(0),                            // 0: Proto.Comandos
	(*SolicitudRecibirComando)(nil),          // 1: Proto.SolicitudRecibirComando
	(*RespuestaRecibirComandoMosEisley)(nil), // 2: Proto.RespuestaRecibirComandoMosEisley
	(*RespuestaRecibirComandoFulcrum)(nil),   // 3: Proto.RespuestaRecibirComandoFulcrum
	(*SolicitudGetNumberRebelds)(nil),        // 4: Proto.SolicitudGetNumberRebelds
	(*RespuestaGetNumberRebelds)(nil),        // 5: Proto.RespuestaGetNumberRebelds
	(*Comando)(nil),                          // 6: Proto.Comando
	(*RelojVector)(nil),                      // 7: Proto.RelojVector
	(*Ubicacion)(nil),                        // 8: Proto.Ubicacion
}
var file_Proto_starwars_proto_depIdxs = []int32{
	6,  // 0: Proto.SolicitudRecibirComando.cmd:type_name -> Proto.Comando
	7,  // 1: Proto.RespuestaRecibirComandoFulcrum.reloj_vec:type_name -> Proto.RelojVector
	8,  // 2: Proto.SolicitudGetNumberRebelds.coord:type_name -> Proto.Ubicacion
	7,  // 3: Proto.RespuestaGetNumberRebelds.reloj_vec:type_name -> Proto.RelojVector
	0,  // 4: Proto.Comando.comando:type_name -> Proto.Comandos
	8,  // 5: Proto.Comando.coord:type_name -> Proto.Ubicacion
	1,  // 6: Proto.MosEisley.RecibirComando:input_type -> Proto.SolicitudRecibirComando
	4,  // 7: Proto.MosEisley.GetNumberRebelds:input_type -> Proto.SolicitudGetNumberRebelds
	1,  // 8: Proto.Fulcrum.RecibirComando:input_type -> Proto.SolicitudRecibirComando
	4,  // 9: Proto.Fulcrum.GetNumberRebelds:input_type -> Proto.SolicitudGetNumberRebelds
	2,  // 10: Proto.MosEisley.RecibirComando:output_type -> Proto.RespuestaRecibirComandoMosEisley
	5,  // 11: Proto.MosEisley.GetNumberRebelds:output_type -> Proto.RespuestaGetNumberRebelds
	3,  // 12: Proto.Fulcrum.RecibirComando:output_type -> Proto.RespuestaRecibirComandoFulcrum
	5,  // 13: Proto.Fulcrum.GetNumberRebelds:output_type -> Proto.RespuestaGetNumberRebelds
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_Proto_starwars_proto_init() }
func file_Proto_starwars_proto_init() {
	if File_Proto_starwars_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Proto_starwars_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SolicitudRecibirComando); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_starwars_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespuestaRecibirComandoMosEisley); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_starwars_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespuestaRecibirComandoFulcrum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_starwars_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SolicitudGetNumberRebelds); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_starwars_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespuestaGetNumberRebelds); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_starwars_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Comando); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_starwars_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RelojVector); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_starwars_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ubicacion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Proto_starwars_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_Proto_starwars_proto_goTypes,
		DependencyIndexes: file_Proto_starwars_proto_depIdxs,
		EnumInfos:         file_Proto_starwars_proto_enumTypes,
		MessageInfos:      file_Proto_starwars_proto_msgTypes,
	}.Build()
	File_Proto_starwars_proto = out.File
	file_Proto_starwars_proto_rawDesc = nil
	file_Proto_starwars_proto_goTypes = nil
	file_Proto_starwars_proto_depIdxs = nil
}
